var myString;
var myNum;
var myBool;
var myVar;
/*
let strArray: string[];
let numArray: number[];
let boolArray: boolean[];
*/
var strArray;
var numArray;
var boolArray;
var strNumTuple;
var myVoid = undefined;
var myNull = null;
var myUndefined = undefined;
myString = 'Hello' + ' ' + 'World'.slice(0, 3);
myNum = 22;
myBool = true;
myVar = 5;
strArray = ['Hello', 'World'];
numArray = [1, 2, 3, 4, 5];
boolArray = [true, false, false, true];
strNumTuple = ['one', 1];
console.log(myString, myNum, myBool, myVar);
console.log(strArray);
console.log(numArray);
console.log(boolArray);
console.log(strNumTuple);
console.log(myVoid);
